In [13]:
class Employee:
  count=0
  def __init__(self,name,family,salary,department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.count+=1
  def average_salary(employees):
    totalSalary=sum(emp.salary for emp in employees)
    return totalSalary/len(employees) if employees else 0
class fulltimeEmployee(Employee):
  def _init_(self,name,family,salary,department):
    super()._init_(name, family, salary, department)
emp1 = Employee("sriram","lakkireddy",90890,"IT")
emp2 = Employee("mani","aru",78909,'Financial')
fulltime_emp1=fulltimeEmployee("vani","chin",678543,"Tech")
fulltime_emp2=fulltimeEmployee("sai","deep",87643,"HR")
emps=[emp1,emp2,fulltime_emp1]
print(Employee.count)
print(Employee.average_salary(emps))


4
282780.6666666667


In [16]:
import numpy as np
vector=np.random.uniform(6,7,20)
array=vector.reshape(4,5)
array[np.arange(4),array.argmax(axis=1)]=0
print(array)

[[6.33773689 6.59728773 6.62076278 0.         6.22331329]
 [6.55597964 0.         6.33396004 6.71391505 6.21698696]
 [6.80811293 6.2291844  6.54606145 6.69399656 0.        ]
 [6.33095765 6.4616452  6.44789043 0.         6.24496134]]


Video Presentation:
https://drive.google.com/file/d/1Lm4z518tVj8sj9P4iH3bvohUeUWCMkLb/view?usp=drive_link